import React from 'react';
import { InlineTool } from 'editorjs-inline-tool';

class MyInlineTool extends InlineTool {
  constructor(props) {
    super(props);
    
    // Set initial state
    this.state = {
      // Add any custom state here
    };

    // Bind your methods to 'this'
    this.onClick = this.onClick.bind(this);
  }

  static get sanitize() {
    return {
      // Define how to clean the content generated by your inline tool
    };
  }

  /**
   * Return current toolbar icon.
   *
   * @return {HTMLElement}
   * @public
   */
  renderActions() {
    const onClick = (e) => this.onClick(e);

    return (
      <div className="my-inline-tool" onClick={onClick}>
        <div>
          This is my custom inline tool
        </div>
      </div>
    )
  }

  onClick(e) {
    // Handle click event on the inline tool.
  }
}

export default MyInlineTool;